export const userTypes = {
  
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

  FETCH_LOGIN_REQUEST: "FETCH_LOGIN_REQUEST",
  FETCH_LOGIN_SUCCESS: "FETCH_LOGIN_SUCCESS",
  FETCH_LOGIN_FAILURE: "FETCH_LOGIN_FAILURE",
  
  FETCH_FORGOT_PASSWORD_REQUEST: "FETCH_FORGOT_PASSWORD_REQUEST",
  FETCH_FORGOT_PASSWORD_SUCCESS: "FETCH_FORGOT_PASSWORD_SUCCESS",
  FETCH_FORGOT_PASSWORD_FAILURE: "FETCH_FORGOT_PASSWORD_FAILURE",

  FETCH_USERDETAILS_REQUEST: "FETCH_USERDETAILS_REQUEST",
  FETCH_USERDETAILS_SUCCESS: "FETCH_USERDETAILS_SUCCESS",
  FETCH_USERDETAILS_FAILURE: "FETCH_USERDETAILS_FAILURE",

  FETCH_LOGOUT:"FETCH_LOGOUT"
};

export const announceTypes = {
  POST_ANNOUNCEMENT_REQUEST: "POST_ANNOUNCEMENT_REQUEST",
  POST_ANNOUNCEMENT_SUCCESS: "POST_ANNOUNCEMENT_SUCCESS",
  POST_ANNOUNCEMENT_FAILURE: "POST_ANNOUNCEMENT_FAILURE",
  // GET_ANNOUNCEMENT_REQUEST: "GET_ANNOUNCEMENT_REQUEST",
  // GET_ANNOUNCEMENT_SUCCESS: "GET_ANNOUNCEMENT_SUCCESS",
  // GET_ANNOUNCEMENT_FAILURE: "GET_ANNOUNCEMENT_FAILURE",
};

export const resetPass_Types = {
  FETCH_RESETPASSWORD_REQUEST: "FETCH_RESETPASSWORD_REQUEST",
  FETCH_RESETPASSWORD_SUCCESS: "FETCH_RESETPASSWORD_SUCCESS",
  FETCH_RESETPASSWORD_FAILURE: "FETCH_RESETPASSWORD_FAILURE:",
};

export const library_Types = {
  FETCH_POSTLIBRARY_REQUEST: "FETCH_POSTLIBRARY_REQUEST",
  FETCH_POSTLIBRARY_SUCCESS: "FETCH_POSTLIBRARY_SUCCESS",
  FETCH_POSTLIBRARY_FAILURE: "FETCH_POSTLIBRARY_FAILURE",

}
